import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import path from "path";
import { exec } from "child_process";
import { sassPlugin } from "esbuild-sass-plugin";

import * as babel from "@babel/core";
import BabelPluginReactCompiler from "babel-plugin-react-compiler";
import babelPluginSyntaxJsx from "@babel/plugin-syntax-jsx";
import babelPluginTransformTypescript from "@babel/plugin-transform-typescript";
import babelPluginTransformTypescriptMetadata from "babel-plugin-transform-typescript-metadata";
import babelPluginProposalDecorators from "@babel/plugin-proposal-decorators";
import babelPluginTransformClassProperties from "@babel/plugin-transform-class-properties";

const isDevelopment = process.argv.includes("--development");
const __dirname = path.dirname(new URL(import.meta.url).pathname);

const banner = {
  js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/`
};

const compilerIssues = [];

const reactCompilerEsbuildPlugin = {
  name: "react-compiler",
  setup(build) {
    build.onLoad({ filter: /\.[jt]sx?$/ }, async (args) => {
      if (args.path.includes("node_modules")) {
        return null;
      }

      const source = await fs.promises.readFile(args.path, "utf8");
      const isTsx = args.path.endsWith(".tsx");
      const isTs = args.path.endsWith(".ts");
      const isJsx = args.path.endsWith(".jsx");

      try {
        const result = await babel.transformAsync(source, {
          filename: args.path,
          assumptions: {
            setPublicClassFields: true,
          },
          presets: [],
          plugins: [
            babelPluginSyntaxJsx, 
            
            babelPluginTransformTypescriptMetadata,
            
            [
              babelPluginTransformTypescript,
              {
                isTSX: isTsx || isJsx,        
                allExtensions: isTsx || isJsx, 
              },
            ],
            
            [babelPluginProposalDecorators, { version: "legacy" }],
            
            babelPluginTransformClassProperties,
            
            [
              BabelPluginReactCompiler,
              {
                panicThreshold: "none", 
                logger: {
                  logEvent(filename, event) {
                    const relativePath = filename ? path.relative(process.cwd(), filename) : "unknown";

                    if (event.kind === "CompileError" || event.kind === "CompileDiagnostic") {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.detail.reason,
                        loc: event.detail.loc || event.fnLoc,
                      });
                    } else if (event.kind === "CompileSkip") {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.reason,
                        loc: event.loc || event.fnLoc,
                      });
                    } else if (event.kind === "CompileUnexpectedThrow" || event.kind === "PipelineError") {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.data,
                        loc: event.fnLoc,
                      });
                    }
                  },
                },
              },
            ],
          ],
          sourceMaps: isDevelopment ? "inline" : false,
          configFile: false,
          babelrc: false,
        });

        if (!result || !result.code) {
          return null;
        }

        let loader = "js";
        if (isTsx) {
          loader = "tsx";
        } else if (isTs) {
          loader = "ts";
        } else if (isJsx) {
          loader = "jsx";
        }

        return {
          contents: result.code,
          loader,
        };
      } catch (err) {
        return {
          errors: [
            {
              text: err.message || String(err),
              location: {
                file: args.path,
                line: err.loc?.line,
                column: err.loc?.column,
              },
            },
          ],
        };
      }
    });
  },
};

async function runTask(name, command) {
  return new Promise((resolve) => {
    exec(command, (error, stdout, stderr) => {
      resolve({
        name,
        success: !error,
        output: (stdout + stderr).trim(),
      });
    });
  });
}

function printReport({ lintResult, typeResult, compilerIssues, buildSuccess, buildError, startTime }) {
  const duration = ((Date.now() - startTime) / 1000).toFixed(2);
  
  console.log("\n" + "═".repeat(60));
  console.log("                     🏗️  FINAL BUILD REPORT");
  console.log("═".repeat(60));

  console.log("\n🔍 ESLINT:");
  if (lintResult.success) {
    console.log("   ✅ Passed");
  } else {
    console.log("   ⚠️  Issues found");
    if (lintResult.output) {
      console.log("   " + "─".repeat(45));
      lintResult.output.split('\n').forEach(line => console.log(`   ${line}`));
      console.log("   " + "─".repeat(45));
    }
  }

  console.log("\n📋 TYPESCRIPT:");
  if (typeResult.success) {
    console.log("   ✅ No errors");
  } else {
    console.log("   ⚠️  Errors detected (non-fatal)");
    if (typeResult.output) {
      console.log("   " + "─".repeat(45));
      typeResult.output.split('\n').forEach(line => console.log(`   ${line}`));
      console.log("   " + "─".repeat(45));
    }
  }

  console.log("\n⚡ REACT COMPILER:");
  if (compilerIssues.length === 0) {
    console.log("   ✅ All components & hooks optimized successfully");
  } else {
    console.log(`   ⚠️  Optimization bypassed for ${compilerIssues.length} components/hooks`);
    console.log("   " + "─".repeat(45));
    compilerIssues.forEach((issue, idx) => {
      const lineCol = issue.loc 
        ? `:${issue.loc.start.line}:${issue.loc.start.column}` 
        : '';
      console.log(`   [${idx + 1}] 📂 ${issue.filename}${lineCol}`);
      console.log(`       ❌ Reason: ${issue.reason}`);
    });
    console.log("   " + "─".repeat(45));
  }

  console.log("\n🎯 BUNDLE:");
  if (buildSuccess) {
    console.log(`   ✅ Success (${duration}s)`);
    
    const outdir = "assets";
    if (fs.existsSync(outdir)) {
      const files = fs.readdirSync(outdir);
      const jsFiles = files.filter(f => f.endsWith('.js'));
      const cssFiles = files.filter(f => f.endsWith('.css'));
      
      if (jsFiles.length > 0 || cssFiles.length > 0) {
        console.log("\n📁 OUTPUT FILES:");
        [...jsFiles, ...cssFiles].forEach(file => {
          const stats = fs.statSync(path.join(outdir, file));
          const sizeKB = (stats.size / 1024).toFixed(2);
          console.log(`   • ${file} (${sizeKB} KB)`);
        });
      }
    }
  } else {
    console.log("   ❌ Failed");
    if (buildError) {
      console.log("   " + "─".repeat(45));
      console.error(`   ${buildError.message || buildError}`);
      console.log("   " + "─".repeat(45));
    }
  }

  console.log("\n" + "═".repeat(60) + "\n");
}

async function runBuild() {
  const startTime = Date.now();
  console.log(`\n🚀 Starting build in ${isDevelopment ? "development" : "production"} mode...\n`);

  compilerIssues.length = 0;

  const lintTask = runTask("ESLint", "npx eslint src");
  const typeCheckTask = runTask("TypeScript", "npx tsc --noEmit --project .");

  let buildSuccess = false;
  let buildError = null;

  try {
    const cssEntry = ["src/styles.scss", "src/styles.css"].find(f => fs.existsSync(f));

    await esbuild.build({
      entryPoints: ["src/main.ts", ...(cssEntry ? [cssEntry] : [])],
      bundle: true,
      platform: "browser",
      format: "cjs",
      target: "es2020",
      outdir: "assets",
      banner,
      minify: !isDevelopment,
      minifyWhitespace: !isDevelopment,
      minifyIdentifiers: !isDevelopment,
      minifySyntax: !isDevelopment,
      sourcemap: isDevelopment ? "inline" : false,
      treeShaking: true,
      legalComments: "none",
      jsx: "automatic",
      keepNames: true,
      
      alias: {
        "@": path.resolve("src"),
      },

      external: [
        "obsidian",
        "node:*",
        "fs", "path", "os", "crypto", "buffer", "stream", "util", "events", "url", "child_process", "module", "electron", "worker_threads"
      ],

      define: {
        "process.env.NODE_ENV": JSON.stringify(isDevelopment ? "development" : "production"),
        "global": "window",
        "__filename": "'main.js'",
        "__dirname": "'.'",
        "Buffer": "undefined",
      },

      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          useDefineForClassFields: true,
        },
      },

      plugins: [
        reactCompilerEsbuildPlugin,
        sassPlugin({
          filter: /\.scss$/,
        }),
      ],
      
      logLevel: "info",
    });

    buildSuccess = true;
  } catch (e) {
    buildError = e;
  }

  const [lintResult, typeResult] = await Promise.all([lintTask, typeCheckTask]);

  printReport({
    lintResult,
    typeResult,
    compilerIssues,
    buildSuccess,
    buildError,
    startTime,
  });

  if (!buildSuccess) {
    process.exit(1);
  }
}

runBuild().catch(err => {
  console.error("\n💥 Fatal error during build process:", err);
  process.exit(1);
});
