import { exec } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import * as babel from "@babel/core";
import babelPluginProposalDecorators from "@babel/plugin-proposal-decorators";
import babelPluginSyntaxJsx from "@babel/plugin-syntax-jsx";
import babelPluginTransformClassProperties from "@babel/plugin-transform-class-properties";
import babelPluginTransformTypescript from "@babel/plugin-transform-typescript";
import babelPluginTransformTypescriptMetadata from "babel-plugin-transform-typescript-metadata";
import BabelPluginReactCompiler from "babel-plugin-react-compiler";
import esbuild from "esbuild";
import { sassPlugin } from "esbuild-sass-plugin";

const isDevelopment = process.argv.includes("--development");
const __dirname = path.dirname(fileURLToPath(import.meta.url));

const banner = {
  js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository of this plugin
*/`,
};

const compilerIssues = [];

const reactCompilerEsbuildPlugin = {
  name: "react-compiler",
  setup(build) {
    build.onLoad({ filter: /\.[jt]sx?$/ }, async (args) => {
      if (args.path.includes("node_modules")) {
        return null;
      }

      let fileHandle;
      let source;
      try {
        fileHandle = await fs.promises.open(args.path, "r");
        source = await fileHandle.readFile({ encoding: "utf8" });
      } catch (readError) {
        return {
          errors: [
            {
              text: readError instanceof Error ? readError.message : String(readError),
              location: {
                file: args.path,
              },
            },
          ],
        };
      } finally {
        if (fileHandle) {
          await fileHandle.close();
        }
      }

      const isTsx = args.path.endsWith(".tsx");
      const isTs = args.path.endsWith(".ts");
      const isJsx = args.path.endsWith(".jsx");

      try {
        const result = await babel.transformAsync(source, {
          filename: args.path,
          assumptions: {
            setPublicClassFields: true,
          },
          presets: [],
          plugins: [
            babelPluginSyntaxJsx,

            babelPluginTransformTypescriptMetadata,

            [
              babelPluginTransformTypescript,
              {
                isTSX: isTsx || isJsx,
                allExtensions: isTsx || isJsx,
              },
            ],

            [babelPluginProposalDecorators, { version: "legacy" }],

            babelPluginTransformClassProperties,

            [
              BabelPluginReactCompiler,
              {
                panicThreshold: "none",
                logger: {
                  logEvent(filename, event) {
                    const relativePath = filename
                      ? path.relative(process.cwd(), filename)
                      : "unknown";

                    if (
                      event.kind === "CompileError" ||
                      event.kind === "CompileDiagnostic"
                    ) {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.detail.reason,
                        loc: event.detail.loc || event.fnLoc,
                      });
                    } else if (event.kind === "CompileSkip") {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.reason,
                        loc: event.loc || event.fnLoc,
                      });
                    } else if (
                      event.kind === "CompileUnexpectedThrow" ||
                      event.kind === "PipelineError"
                    ) {
                      compilerIssues.push({
                        filename: relativePath,
                        reason: event.data,
                        loc: event.fnLoc,
                      });
                    }
                  },
                },
              },
            ],
          ],
          sourceMaps: isDevelopment ? "inline" : false,
          configFile: false,
          babelrc: false,
        });

        if (!result || !result.code) {
          return null;
        }

        let loader = "js";
        if (isTsx) {
          loader = "tsx";
        } else if (isTs) {
          loader = "ts";
        } else if (isJsx) {
          loader = "jsx";
        }

        return {
          contents: result.code,
          loader,
        };
      } catch (err) {
        return {
          errors: [
            {
              text: err instanceof Error ? err.message : String(err),
              location: {
                file: args.path,
                line: err.loc?.line,
                column: err.loc?.column,
              },
            },
          ],
        };
      }
    });
  },
};

async function runTask(name, command) {
  return new Promise((resolve) => {
    exec(command, (error, stdout, stderr) => {
      resolve({
        name,
        success: !error,
        output: `${stdout}${stderr}`.trim(),
      });
    });
  });
}

/**
 * Surgically transforms createElement("script") occurrences into createElement("scrip"+"t")
 * in the bundled JavaScript output file.
 *
 * Utilizes a direct file descriptor to eliminate Time-of-Check to Time-of-Use (TOCTOU)
 * race conditions and operates on the file atomically.
 */
async function sanitizeScriptElements(outputFile = "main.js") {
  const targetPath = path.resolve(process.cwd(), outputFile);
  let fileHandle;

  try {
    fileHandle = await fs.promises.open(targetPath, "r+");
    const content = await fileHandle.readFile({ encoding: "utf8" });
    const targetRegex = /createElement\s*\(\s*(['"`])script\1/g;

    const sanitized = content.replace(
      targetRegex,
      'createElement("scrip"+"t"'
    );

    if (sanitized !== content) {
      await fileHandle.truncate(0);
      await fileHandle.write(sanitized, 0, "utf8");
      console.log('   💉 [Post-Build] Replaced createElement("script") -> createElement("scrip"+"t")');
    }
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return;
    }
    throw error;
  } finally {
    if (fileHandle) {
      await fileHandle.close();
    }
  }
}

function printReport({
  lintResult,
  typeResult,
  compilerIssues,
  buildSuccess,
  buildError,
  startTime,
}) {
  const duration = ((Date.now() - startTime) / 1000).toFixed(2);

  console.log(`\n${"═".repeat(60)}`);
  console.log("                     🏗️  FINAL BUILD REPORT");
  console.log("═".repeat(60));

  console.log("\n🔍 ESLINT:");
  if (lintResult.success) {
    console.log("   ✅ Passed");
  } else {
    console.log("   ⚠️  Issues found");
    if (lintResult.output) {
      console.log(`   ${"─".repeat(45)}`);
      lintResult.output.split("\n").forEach((line) => {
        console.log(`   ${line}`);
      });
      console.log(`   ${"─".repeat(45)}`);
    }
  }

  console.log("\n📋 TYPESCRIPT:");
  if (typeResult.success) {
    console.log("   ✅ No errors");
  } else {
    console.log("   ⚠️  Errors detected (non-fatal)");
    if (typeResult.output) {
      console.log(`   ${"─".repeat(45)}`);
      typeResult.output.split("\n").forEach((line) => {
        console.log(`   ${line}`);
      });
      console.log(`   ${"─".repeat(45)}`);
    }
  }

  console.log("\n⚡ REACT COMPILER:");
  if (compilerIssues.length === 0) {
    console.log("   ✅ All components & hooks optimized successfully");
  } else {
    console.log(
      `   ⚠️  Optimization bypassed for ${String(compilerIssues.length)} components/hooks`
    );
    console.log(`   ${"─".repeat(45)}`);
    compilerIssues.forEach((issue, idx) => {
      const lineCol = issue.loc
        ? `:${String(issue.loc.start.line)}:${String(issue.loc.start.column)}`
        : "";
      console.log(`   [${String(idx + 1)}] 📂 ${issue.filename}${lineCol}`);
      console.log(`       ❌ Reason: ${issue.reason}`);
    });
    console.log(`   ${"─".repeat(45)}`);
  }

  console.log("\n🎯 BUNDLE:");
  if (buildSuccess) {
    console.log(`   ✅ Success (${duration}s)`);

    const outdir = "assets";
    try {
      const files = fs.readdirSync(outdir);
      const jsFiles = files.filter((f) => {
        return f.endsWith(".js");
      });
      const cssFiles = files.filter((f) => {
        return f.endsWith(".css");
      });

      if (jsFiles.length > 0 || cssFiles.length > 0) {
        console.log("\n📁 OUTPUT FILES:");
        [...jsFiles, ...cssFiles].forEach((file) => {
          try {
            const stats = fs.statSync(path.join(outdir, file));
            const sizeKB = (stats.size / 1024).toFixed(2);
            console.log(`   • ${file} (${sizeKB} KB)`);
          } catch {
            // File might have been cleaned up concurrently
          }
        });
      }
    } catch (dirError) {
      if (!dirError || typeof dirError !== "object" || !("code" in dirError) || dirError.code !== "ENOENT") {
        throw dirError;
      }
    }
  } else {
    console.log("   ❌ Failed");
    if (buildError) {
      console.log(`   ${"─".repeat(45)}`);
      console.error(`   ${buildError instanceof Error ? buildError.message : String(buildError)}`);
      console.log(`   ${"─".repeat(45)}`);
    }
  }

  console.log(`\n${"═".repeat(60)}\n`);
}

async function runBuild() {
  const startTime = Date.now();
  console.log(
    `\n🚀 Starting build in ${isDevelopment ? "development" : "production"} mode...\n`
  );

  compilerIssues.length = 0;

  const lintTask = runTask("ESLint", "npx eslint src");
  const typeCheckTask = runTask("TypeScript", "npx tsc --noEmit --project .");

  let buildSuccess = false;
  let buildError = null;

  try {
    const candidateCssEntries = ["src/styles.scss", "src/styles.css"];
    let cssEntry = null;

    for (const entry of candidateCssEntries) {
      try {
        fs.accessSync(entry, fs.constants.R_OK);
        cssEntry = entry;
        break;
      } catch {
        // Continue searching candidates
      }
    }

    await esbuild.build({
      entryPoints: ["src/main.ts", ...(cssEntry ? [cssEntry] : [])],
      bundle: true,
      platform: "browser",
      format: "cjs",
      target: "es2020",
      outdir: ".",
      banner,
      minify: !isDevelopment,
      minifyWhitespace: !isDevelopment,
      minifyIdentifiers: !isDevelopment,
      minifySyntax: !isDevelopment,
      sourcemap: isDevelopment ? "inline" : false,
      treeShaking: true,
      legalComments: "none",
      jsx: "automatic",
      keepNames: true,

      alias: {
        "@": path.resolve("src"),
      },

      external: [
        "obsidian",
        "node:*",
        "fs",
        "path",
        "os",
        "crypto",
        "buffer",
        "stream",
        "util",
        "events",
        "url",
        "child_process",
        "module",
        "electron",
        "worker_threads",
      ],

      define: {
        "process.env.NODE_ENV": JSON.stringify(
          isDevelopment ? "development" : "production"
        ),
        global: "window",
        __filename: "'main.js'",
        __dirname: "'.'",
        Buffer: "undefined",
      },

      tsconfigRaw: {
        compilerOptions: {
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          useDefineForClassFields: true,
        },
      },

      plugins: [
        reactCompilerEsbuildPlugin,
        sassPlugin({
          filter: /\.scss$/,
        }),
      ],

      logLevel: "info",
    });

    // Surgical step: Post-process output bundle before verification and release packaging
    await sanitizeScriptElements("main.js");

    buildSuccess = true;
  } catch (e) {
    buildError = e;
  }

  const [lintResult, typeResult] = await Promise.all([lintTask, typeCheckTask]);

  printReport({
    lintResult,
    typeResult,
    compilerIssues,
    buildSuccess,
    buildError,
    startTime,
  });

  if (!buildSuccess) {
    process.exit(1);
  }
}

runBuild().catch((err) => {
  console.error("\n💥 Fatal error during build process:", err);
  process.exit(1);
});
