import js from "@eslint/js";
import tseslint from "typescript-eslint";
import eslintReact from "@eslint-react/eslint-plugin";
import obsidianmd from "eslint-plugin-obsidianmd";
import globals from "globals";

export default tseslint.config(
  // 1. Global Ignores
  {
    name: "global/ignores",
    ignores: [
      "*.yml",
      "*.yaml",
      "assets/**",
      "*.scss",
      "*.css",
      "*.mjs",
      "node_modules/**",
      "dist/**",
      "coverage/**",
      "package-lock.json",
      "main.js",
      "*.min.js",
    ],
  },

  // 2. Global Linter Options
  {
    linterOptions: {
      reportUnusedDisableDirectives: "error",
    },
  },

  // 3. Base ESLint Recommended Rules
  js.configs.recommended,

  // 4. TypeScript-ESLint Presets (Strict + Stylistic Type-Checked)
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  // 5. ESLint React Strict Type-Checked Preset
  eslintReact.configs["strict-type-checked"],

  // 6. Obsidian Plugin Recommended Preset
  ...obsidianmd.configs.recommended,

  // 7. Custom Overrides & Calibration
  {
    name: "main/typescript-react",
    files: ["**/*.{ts,tsx,mts,cts}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
        ecmaFeatures: {
          jsx: true,
        },
        jsDocParsingMode: "all",
      },
      globals: {
        ...globals.browser,
        ...globals.es2024,
        ...globals.node,
      },
    },
    settings: {
      "react-x": {
        version: "detect",
      },
    },
    rules: {
      // =========================================================================
      // Core JavaScript Rules (Zero False Positives)
      // =========================================================================
      "eqeqeq": ["error", "always"],
      "curly": ["error", "all"],
      "no-constant-condition": ["error", { checkLoops: false }],
      "no-implicit-coercion": ["error", {
        boolean: true,
        number: true,
        string: true,
        disallowTemplateShorthand: true,
        allow: ["!!"],
      }],
      "no-return-assign": ["error", "always"],
      "no-sequences": "error",
      "no-var": "error",
      "prefer-const": ["error", {
        destructuring: "all",
        ignoreReadBeforeAssign: false,
      }],
      "no-unreachable": "error",
      "no-cond-assign": ["error", "always"],
      "no-void": ["error", { allowAsStatement: true }], // Enables safe `void asyncFn()` in attributes
      "no-self-assign": ["error", { props: true }],
      "no-self-compare": "error",
      "no-template-curly-in-string": "error",
      "no-unreachable-loop": "error",
      "no-fallthrough": "error",
      "guard-for-in": "error",
      "no-dupe-else-if": "error",
      "no-eval": "error",
      "no-new-func": "error",
      "no-extend-native": "error",
      "no-new-wrappers": "error",
      "no-new": "error",
      "no-new-native-nonconstructor": "error",
      "no-invalid-regexp": "error",
      "no-constructor-return": "error",
      "no-async-promise-executor": "error",
      "no-promise-executor-return": "error",
      "no-unmodified-loop-condition": "error",
      "accessor-pairs": "error",
      "no-labels": "error",
      "no-caller": "error",
      "no-with": "error",
      "no-octal": "error",
      "no-octal-escape": "error",
      "no-proto": "error",
      "no-sparse-arrays": "error",
      "no-compare-neg-zero": "error",
      "no-ex-assign": "error",
      "no-unsafe-optional-chaining": ["error", { disallowArithmeticOperators: true }],
      "no-constant-binary-expression": "error",
      "no-duplicate-case": "error",
      "no-useless-backreference": "error",
      "no-setter-return": "error",
      "no-lone-blocks": "error",
      "no-extra-boolean-cast": ["error", { enforceForInnerExpressions: true }],
      "symbol-description": "error",
      "valid-typeof": ["error", { requireStringLiterals: true }],
      "no-delete-var": "error",
      "no-unsafe-negation": ["error", { enforceForOrderingRelations: true }],
      "use-isnan": ["error", { enforceForSwitchCase: true, enforceForIndexOf: true }],
      "getter-return": "error",
      "for-direction": "error",
      "radix": ["error", "as-needed"],
      "no-debugger": "error",
      "no-irregular-whitespace": "error",
      "no-alert": "error",
      "no-script-url": "error",
      "no-multi-str": "error",
      "no-useless-catch": "error",
      "no-useless-concat": "error",
      "no-useless-escape": "error",
      "no-useless-rename": "error",
      "no-useless-return": "error",
      "no-useless-call": "error",
      "no-useless-computed-key": ["error", { enforceForClassMembers: true }],
      "no-param-reassign": ["error", { props: false }],
      "no-else-return": ["error", { allowElseIf: true }],
      "no-lonely-if": "error",
      "no-unneeded-ternary": ["error", { defaultAssignment: false }],
      "no-nested-ternary": "off",
      "no-bitwise": "off",
      "no-empty": ["error", { allowEmptyCatch: true }],
      "no-extra-label": "error",
      "no-label-var": "error",
      "no-shadow-restricted-names": "error",
      "no-undef-init": "error",
      "prefer-object-spread": "error",
      "prefer-object-has-own": "error",
      "prefer-template": "error",
      "prefer-rest-params": "error",
      "prefer-spread": "error",
      "prefer-arrow-callback": ["error", { allowNamedFunctions: true, allowUnboundThis: true }],
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "error",
      "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
      "prefer-exponentiation-operator": "error",
      "object-shorthand": ["error", "always", {
        avoidQuotes: true,
        ignoreConstructors: false,
        avoidExplicitReturnArrows: false,
      }],
      "default-case-last": "error",
      "grouped-accessor-pairs": ["error", "anyOrder"],
      "no-implicit-globals": "error",
      "no-iterator": "error",
      "no-restricted-globals": ["error", "fdescribe"],
      "no-object-constructor": "error",
      "no-unused-private-class-members": "error",
      "require-atomic-updates": "off",
      "no-loss-of-precision": "error",

      // =========================================================================
      // Disabled in Favor of TypeScript / Compiler Counterparts
      // =========================================================================
      "no-undef": "off", // Handled by TypeScript type-checker
      "consistent-return": "off",
      "no-throw-literal": "off",
      "no-useless-constructor": "off",
      "no-unused-expressions": "off",
      "no-implied-eval": "off",
      "no-use-before-define": "off",
      "no-return-await": "off",
      "no-shadow": "off",
      "dot-notation": "off",
      "no-array-constructor": "off",
      "no-unused-vars": "off",
      "no-dupe-class-members": "off",
      "no-invalid-this": "off",
      "no-loop-func": "off",
      "no-redeclare": "off",
      "default-param-last": "off",
      "no-empty-function": "off",
      "require-await": "off",
      "init-declarations": "off",
      "class-methods-use-this": "off",
      "max-params": "off",
      "prefer-promise-reject-errors": "off",

      // =========================================================================
      // TypeScript Strict & Calibrated Rules
      // =========================================================================
      // [RULE 1 & 3]: Strictly catches assertions that do not narrow or whose receiver already accepts the type
      "@typescript-eslint/no-unnecessary-type-assertion": "error",

      // [RULE 2]: Strictly catches promise-returning functions provided to attributes, arguments, returns, etc.
      "@typescript-eslint/no-misused-promises": ["error", {
        checksConditionals: true,
        checksVoidReturn: {
          arguments: true,
          attributes: true,  // Enforces strict attribute void return checking
          properties: true,
          returns: true,
          variables: true,
          inheritedMethods: true,
        },
        checksSpreads: true,
      }],

      "@typescript-eslint/consistent-return": "error",
      "@typescript-eslint/no-unnecessary-condition": ["error", {
        allowConstantLoopConditions: "always",
        checkTypePredicates: false,
      }],
      "@typescript-eslint/no-unnecessary-type-constraint": "error",
      "@typescript-eslint/no-unnecessary-type-arguments": "error",
      "@typescript-eslint/no-unnecessary-type-conversion": "error",
      "@typescript-eslint/no-unnecessary-template-expression": "error",
      "@typescript-eslint/no-unnecessary-qualifier": "error",
      "@typescript-eslint/no-unnecessary-parameter-property-assignment": "error",
      "@typescript-eslint/no-unnecessary-type-parameters": "error",
      "@typescript-eslint/no-unnecessary-boolean-literal-compare": ["error", {
        allowComparingNullableBooleansToTrue: true,
        allowComparingNullableBooleansToFalse: true,
      }],
      "@typescript-eslint/no-inferrable-types": ["error", {
        ignoreParameters: false,
        ignoreProperties: false,
      }],
      "@typescript-eslint/no-deprecated": "error",
      "@typescript-eslint/unbound-method": ["error", {
        ignoreStatic: true,
      }],
      "@typescript-eslint/non-nullable-type-assertion-style": "error",
      "@typescript-eslint/switch-exhaustiveness-check": ["error", {
        allowDefaultCaseForExhaustiveSwitch: true,
        requireDefaultForNonUnion: true,
        considerDefaultExhaustiveForUnions: true,
      }],
      "@typescript-eslint/only-throw-error": "error",
      "@typescript-eslint/prefer-promise-reject-errors": ["error", {
        allowEmptyReject: true,
      }],
      "@typescript-eslint/dot-notation": ["error", {
        allowKeywords: true,
        allowPrivateClassPropertyAccess: true,
        allowProtectedClassPropertyAccess: true,
        allowIndexSignaturePropertyAccess: true,
      }],
      "@typescript-eslint/no-shadow": ["error", {
        builtinGlobals: false,
        hoist: "functions",
        allow: ["_"],
        ignoreOnInitialization: true,
        ignoreTypeValueShadow: true,
        ignoreFunctionTypeParameterNameValueShadow: true,
      }],
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/prefer-readonly-parameter-types": "off",
      "@typescript-eslint/require-array-sort-compare": ["error", {
        ignoreStringArrays: false,
      }],
      "@typescript-eslint/no-unsafe-argument": "error",
      "@typescript-eslint/no-unsafe-assignment": "error",
      "@typescript-eslint/no-unsafe-call": "error",
      "@typescript-eslint/no-unsafe-member-access": "error",
      "@typescript-eslint/no-unsafe-return": "error",
      "@typescript-eslint/no-unsafe-enum-comparison": "error",
      "@typescript-eslint/no-unsafe-type-assertion": "off",
      "@typescript-eslint/no-unsafe-declaration-merging": "error",
      "@typescript-eslint/no-unsafe-unary-minus": "error",
      "@typescript-eslint/no-explicit-any": ["error", {
        fixToUnknown: false,
        ignoreRestArgs: true,
      }],
      "@typescript-eslint/no-non-null-assertion": "off", // Allowed for valid DOM/Map lookups; caught by no-unnecessary-type-assertion if redundant
      "@typescript-eslint/no-non-null-asserted-optional-chain": "error",
      "@typescript-eslint/no-extra-non-null-assertion": "error",
      "@typescript-eslint/consistent-type-assertions": ["error", {
        assertionStyle: "as",
        objectLiteralTypeAssertions: "allow-as-parameter",
      }],
      "@typescript-eslint/no-unused-vars": ["error", {
        args: "all",
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
      }],
      "@typescript-eslint/no-unused-expressions": ["error", {
        allowShortCircuit: true,
        allowTernary: true,
        allowTaggedTemplates: true,
        enforceForJSX: false,
      }],
      "@typescript-eslint/no-implied-eval": "error",
      "@typescript-eslint/no-use-before-define": ["error", {
        functions: false,
        classes: true,
        variables: true,
        enums: true,
        typedefs: false,
        ignoreTypeReferences: true,
      }],
      "@typescript-eslint/ban-ts-comment": ["error", {
        "ts-expect-error": "allow-with-description",
        "ts-ignore": "allow-with-description",
        "ts-nocheck": true,
        "ts-check": false,
        minimumDescriptionLength: 3,
      }],
      "@typescript-eslint/prefer-ts-expect-error": "error",
      "@typescript-eslint/prefer-nullish-coalescing": ["error", {
        ignorePrimitives: {
          bigint: true,
          boolean: true,
          number: true,
          string: true,
        },
        ignoreMixedLogicalExpressions: true,
        ignoreConditionalTests: true,
        ignoreTernaryTests: true,
      }],
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/no-meaningless-void-operator": ["error", {
        checkNever: true,
      }],
      "@typescript-eslint/no-confusing-void-expression": ["error", {
        ignoreArrowShorthand: true,
        ignoreVoidOperator: true,
      }],
      "@typescript-eslint/explicit-function-return-type": ["error", {
        allowExpressions: true,
        allowTypedFunctionExpressions: true,
        allowHigherOrderFunctions: true,
        allowDirectConstAssertionInArrowFunctions: true,
        allowConciseArrowFunctionExpressionsStartingWithVoid: true,
        allowFunctionsWithoutTypeParameters: true,
        allowIIFEs: true,
      }],
      "@typescript-eslint/explicit-member-accessibility": "off",
      "@typescript-eslint/explicit-module-boundary-types": ["error", {
        allowArgumentsExplicitlyTypedAsAny: false,
        allowDirectConstAssertionInArrowFunctions: true,
        allowHigherOrderFunctions: true,
        allowTypedFunctionExpressions: true,
      }],
      "@typescript-eslint/no-redundant-type-constituents": "error",
      "@typescript-eslint/no-duplicate-type-constituents": "error",
      "@typescript-eslint/no-dynamic-delete": "error",
      "@typescript-eslint/no-base-to-string": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", {
        allowNumber: true,
        allowBoolean: true,
        allowAny: false,
        allowNullish: true,
        allowRegExp: true,
        allowNever: true,
      }],
      "@typescript-eslint/restrict-plus-operands": ["error", {
        allowAny: false,
        allowBoolean: false,
        allowNullish: false,
        allowNumberAndString: false,
        allowRegExp: false,
      }],
      "@typescript-eslint/prefer-includes": "error",
      "@typescript-eslint/prefer-string-starts-ends-with": "error",
      "@typescript-eslint/no-misused-spread": "error",
      "@typescript-eslint/prefer-for-of": "error",
      "@typescript-eslint/promise-function-async": "off",
      "@typescript-eslint/unified-signatures": "error",
      "@typescript-eslint/method-signature-style": "off",
      "@typescript-eslint/require-await": "error",
      "@typescript-eslint/prefer-reduce-type-parameter": "error",
      "@typescript-eslint/prefer-as-const": "error",
      "@typescript-eslint/no-extraneous-class": ["error", {
        allowStaticOnly: true,
        allowWithDecorator: true,
        allowConstructorOnly: false,
        allowEmpty: true,
      }],
      "@typescript-eslint/no-invalid-void-type": ["error", {
        allowInGenericTypeArguments: true,
        allowAsThisParameter: true,
      }],
      "@typescript-eslint/use-unknown-in-catch-callback-variable": "error",
      "@typescript-eslint/no-empty-function": ["error", {
        allow: [
          "arrowFunctions",
          "functions",
          "methods",
        ],
      }],
      "@typescript-eslint/no-confusing-non-null-assertion": "error",
      "@typescript-eslint/no-array-constructor": "error",
      "@typescript-eslint/no-array-delete": "error",
      "@typescript-eslint/no-wrapper-object-types": "error",
      "@typescript-eslint/no-empty-object-type": ["error", {
        allowInterfaces: "always",
        allowObjectTypes: "never",
      }],
      "@typescript-eslint/no-unsafe-function-type": "error",
      "@typescript-eslint/prefer-literal-enum-member": ["error", {
        allowBitwiseExpressions: true,
      }],
      "@typescript-eslint/strict-boolean-expressions": ["error", {
        allowString: true,
        allowNumber: true,
        allowNullableObject: true,
        allowNullableBoolean: true,
        allowNullableString: true,
        allowNullableNumber: true,
        allowNullableEnum: true,
        allowAny: true,
      }],
      "@typescript-eslint/default-param-last": "error",
      "@typescript-eslint/init-declarations": "off",
      "@typescript-eslint/no-dupe-class-members": "error",
      "@typescript-eslint/no-invalid-this": ["error", {
        capIsConstructor: false,
      }],
      "@typescript-eslint/no-loop-func": "error",
      "@typescript-eslint/no-redeclare": "error",
      "@typescript-eslint/no-require-imports": "error",
      "@typescript-eslint/no-this-alias": ["error", {
        allowDestructuring: true,
      }],
      "@typescript-eslint/no-floating-promises": ["error", {
        ignoreVoid: true,
        ignoreIIFE: true,
        checkThenables: true,
      }],
      "@typescript-eslint/await-thenable": "error",
      "@typescript-eslint/return-await": ["error", "in-try-catch"],
      "@typescript-eslint/no-useless-constructor": "error",
      "@typescript-eslint/no-useless-empty-export": "error",
      "@typescript-eslint/related-getter-setter-pairs": "error",
      "@typescript-eslint/class-methods-use-this": "off",
      "@typescript-eslint/max-params": ["error", {
        max: 4,
        countVoidThis: false,
      }],
      "@typescript-eslint/consistent-type-imports": "off",
      "@typescript-eslint/consistent-type-exports": ["error", {
        fixMixedExportsWithInlineTypeSpecifier: false,
      }],
      "@typescript-eslint/consistent-type-definitions": "off",
      "@typescript-eslint/consistent-generic-constructors": ["error", "constructor"],
      "@typescript-eslint/consistent-indexed-object-style": ["error", "record"],
      "@typescript-eslint/no-import-type-side-effects": "error",
      "@typescript-eslint/naming-convention": [
        "error",
        {
          selector: "default",
          format: ["camelCase"],
          leadingUnderscore: "allow",
          trailingUnderscore: "forbid",
        },
        {
          selector: "variable",
          format: ["camelCase", "UPPER_CASE", "PascalCase"],
          leadingUnderscore: "allow",
          trailingUnderscore: "forbid",
        },
        {
          selector: ["variable", "parameter"],
          modifiers: ["destructured"],
          format: null,
        },
        {
          selector: "function",
          format: ["camelCase", "PascalCase"],
        },
        {
          selector: "parameter",
          format: ["camelCase", "PascalCase"],
          leadingUnderscore: "allow",
        },
        {
          selector: "typeLike",
          format: ["PascalCase"],
        },
        {
          selector: "enumMember",
          format: ["PascalCase", "UPPER_CASE"],
        },
        {
          selector: ["property", "method", "accessor"],
          format: null,
        },
        {
          selector: "import",
          format: ["camelCase", "PascalCase", "UPPER_CASE"],
        },
      ],
      "@typescript-eslint/prefer-enum-initializers": "error",
      "@typescript-eslint/prefer-return-this-type": "error",
      "@typescript-eslint/prefer-find": "error",
      "@typescript-eslint/prefer-regexp-exec": "error",
      "@typescript-eslint/no-mixed-enums": "error",
      "@typescript-eslint/no-duplicate-enum-values": "error",
    },
  },
);
